version: 2.1

jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: php:8.2.0

    steps:
      - run:
          name: "Prepare Environment"
          command: |
            sudo apt update
            sudo docker-php-ext-install zip